"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import dayjs from "dayjs";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";
import { Icons } from "@/lib/icons";
import { expensesApiService } from "@/services/api.expenses.service";
import { ExpenseCategory, IExpense, IExpensePayload } from "@/types";
import { useToast } from "@/components/ui/toast";

const categories: ExpenseCategory[] = ["RAW_MATERIAL","SALARY","ELECTRICITY","TRANSPORT","MAINTENANCE","RENT","OTHER"];
const emptyForm = (): IExpensePayload => ({ title: "", category: "OTHER", amount: 0, date: dayjs().format("YYYY-MM-DD"), description: "" });

export default function ExpensesPage() {
  const { t } = useTranslation(); const { success, error } = useToast();
  const [month, setMonth] = useState(dayjs().format("YYYY-MM")); const [items, setItems] = useState<IExpense[]>([]); const [loading, setLoading] = useState(true); const [mutating, setMutating] = useState(false); const [form, setForm] = useState<IExpensePayload>(emptyForm()); const [editing, setEditing] = useState<IExpense | null>(null); const [deleting, setDeleting] = useState<IExpense | null>(null); const [dialogOpen, setDialogOpen] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const response = await expensesApiService.getAll(month); setItems(response.items ?? []); } catch (err) { error({ title: t("expensesPage.loadFailed"), description: err instanceof Error ? err.message : undefined }); } finally { setLoading(false); } }, [error, month, t]);
  useEffect(() => { void load(); }, [load]);
  const openCreate = () => { setEditing(null); setForm(emptyForm()); setDialogOpen(true); };
  const openEdit = (item: IExpense) => { setEditing(item); setForm({ title: item.title, category: item.category, amount: item.amount, date: dayjs(item.date).format("YYYY-MM-DD"), description: item.description }); setDialogOpen(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setMutating(true); try { const payload = { ...form, date: new Date(form.date).toISOString() }; if (editing) await expensesApiService.update(editing._id, payload); else await expensesApiService.create(payload); success({ title: t(editing ? "expensesPage.updateSuccess" : "expensesPage.createSuccess") }); setDialogOpen(false); await load(); } catch (err) { error({ title: t("expensesPage.saveFailed"), description: err instanceof Error ? err.message : undefined }); } finally { setMutating(false); } };
  const remove = async () => { if (!deleting) return; setMutating(true); try { await expensesApiService.remove(deleting._id); success({ title: t("expensesPage.deleteSuccess") }); setDeleting(null); await load(); } catch (err) { error({ title: t("expensesPage.deleteFailed"), description: err instanceof Error ? err.message : undefined }); } finally { setMutating(false); } };
  const total = items.reduce((sum, item) => sum + item.amount, 0);
  return <div className="container mx-auto p-6"><div className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-[var(--primary-400)]">{t("expensesPage.badge")}</p><h1 className="mt-2 text-3xl font-bold">{t("expensesPage.title")}</h1><p className="mt-2 text-sm text-[var(--black-100)]">{t("expensesPage.description")}</p></div><div className="flex flex-wrap items-end gap-3"><div className="space-y-2"><Label>{t("expensesPage.month")}</Label><Input type="month" value={month} onChange={(e) => setMonth(e.target.value)} /></div><Button onClick={openCreate}><Icons.add className="h-4 w-4" />{t("expensesPage.add")}</Button></div></div>
    <Card className="mb-5"><CardContent className="flex items-center justify-between py-5"><span className="font-semibold">{t("expensesPage.monthTotal")}</span><strong className="text-2xl text-[var(--primary-500)]">{total.toLocaleString()}</strong></CardContent></Card>
    <Card className="p-0"><CardContent className="px-0 pb-0"><Table><TableHeader><TableRow><TableHead>{t("expensesPage.table.title")}</TableHead><TableHead>{t("expensesPage.table.category")}</TableHead><TableHead>{t("expensesPage.table.amount")}</TableHead><TableHead>{t("expensesPage.table.date")}</TableHead><TableHead>{t("expensesPage.table.description")}</TableHead><TableHead>{t("expensesPage.table.actions")}</TableHead></TableRow></TableHeader><TableBody>{loading ? Array.from({ length: 5 }, (_, i) => <TableRow key={i}><TableCell colSpan={6}><Skeleton className="h-8 w-full" /></TableCell></TableRow>) : items.length === 0 ? <TableRow><TableCell colSpan={6} className="py-10 text-center">{t("expensesPage.empty")}</TableCell></TableRow> : items.map((item) => <TableRow key={item._id}><TableCell className="font-semibold">{item.title}</TableCell><TableCell>{t(`expensesPage.categories.${item.category}`)}</TableCell><TableCell>{item.amount.toLocaleString()}</TableCell><TableCell>{dayjs(item.date).format("YYYY-MM-DD")}</TableCell><TableCell>{item.description || "-"}</TableCell><TableCell><div className="flex gap-2"><Button variant="ghost" size="icon" onClick={() => openEdit(item)}><Icons.edit className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => setDeleting(item)}><Icons.delete className="h-4 w-4 text-[var(--danger)]" /></Button></div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent><DialogHeader><DialogTitle>{t(editing ? "expensesPage.dialog.editTitle" : "expensesPage.dialog.addTitle")}</DialogTitle><DialogDescription>{t("expensesPage.dialog.description")}</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><div className="space-y-2"><Label>{t("expensesPage.dialog.title")}</Label><Input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></div><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>{t("expensesPage.dialog.category")}</Label><Select value={form.category} onValueChange={(value) => setForm({ ...form, category: value as ExpenseCategory })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{categories.map((value) => <SelectItem key={value} value={value}>{t(`expensesPage.categories.${value}`)}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>{t("expensesPage.dialog.amount")}</Label><Input type="number" min="0" required value={form.amount} onChange={(e) => setForm({ ...form, amount: Number(e.target.value) })} /></div><div className="space-y-2"><Label>{t("expensesPage.dialog.date")}</Label><Input type="date" required value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></div></div><div className="space-y-2"><Label>{t("expensesPage.dialog.descriptionField")}</Label><Input value={form.description || ""} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><DialogFooter><Button type="button" variant="outline" onClick={() => setDialogOpen(false)}>{t("expensesPage.dialog.cancel")}</Button><Button type="submit" disabled={mutating}>{t("expensesPage.dialog.save")}</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={Boolean(deleting)} onOpenChange={(open) => !open && setDeleting(null)}><DialogContent><DialogHeader><DialogTitle>{t("expensesPage.dialog.deleteTitle")}</DialogTitle><DialogDescription>{t("expensesPage.dialog.deleteDescription")}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeleting(null)}>{t("expensesPage.dialog.cancel")}</Button><Button variant="destructive" onClick={() => void remove()} disabled={mutating}>{t("expensesPage.dialog.delete")}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
